In [11]:
# И то и другое — оба условия должны быть True
df[(df['возраст'] > 20) & (df['зарплата'] > 60000)]

NameError: name 'df' is not defined

In [ ]:
import requests
print(requests.__version__)

2.34.2

In [14]:
import requests

# Запрос к открытому API — информация о стране
r = requests.get('https://restcountries.com/v3.1/name/russia')

# Смотрим что вернул сервер
print(r.status_code)
print(type(r.json()))

200
<class 'dict'>

In [ ]:
# Увеличить каждую зарплату на 10%
df_dirty['зарплата'].apply(lambda x: x * 1.1)

0    38500.0
1    99000.0
2    66000.0
3    82500.0
4        NaN
Name: зарплата, dtype: float64

In [16]:
# Достаём данные из ответа
data = r.json()

# JSON пришёл как список — берём первый элемент
country = data[0]

# Смотрим какие ключи есть
print(country.keys())

KeyError: 0

In [17]:
data = r.json()
print(type(data))
print(data)

<class 'dict'>
{'success': False, 'data': None, 'errors': [{'message': 'This API version has been deprecated. Please visit https://restcountries.com/docs/countries/legacy-api-deprecation to migrate to our new version (v5).'}]}

In [18]:
r = requests.get('https://restcountries.com/v3.1/name/russia')
data = r.json()
print(type(data))
print(data[0].keys())

<class 'dict'>

KeyError: 0

In [19]:
r = requests.get('https://restcountries.com/v3.1/name/russia')
data = r.json()
print(data.keys())

dict_keys(['success', 'data', 'errors'])

In [20]:
r = requests.get('https://wttr.in/Perm?format=j1')
data = r.json()
print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['current_condition', 'nearest_area', 'request', 'weather'])

In [21]:
# Текущая погода в Перми
current = data['current_condition'][0]

print('Температура:', current['temp_C'], '°C')
print('Ощущается как:', current['FeelsLikeC'], '°C')
print('Влажность:', current['humidity'], '%')
print('Описание:', current['weatherDesc'][0]['value'])

Температура: 16 °C
Ощущается как: 16 °C
Влажность: 71 %
Описание: Sunny

In [22]:
# Прогноз на несколько дней из того же ответа
weather_days = data['weather']

rows = []
for day in weather_days:
    rows.append({
        'дата': day['date'],
        'макс_темп': day['maxtempC'],
        'мин_темп': day['mintempC'],
        'осадки_мм': day['hourly'][0]['precipMM']
    })

df_weather = pd.DataFrame(rows)
df_weather

         дата макс_темп мин_темп осадки_мм
0  2026-09-27        18        8       0.0
1  2026-09-28        17        9       0.0
2  2026-09-29        16        9       0.0

In [ ]:
# Привести имена к верхнему регистру
df_dirty['имя'].apply(lambda x: x.upper())

0    НИКИТА
1      АННА
2      ИВАН
3     МАРИЯ
4      ОЛЕГ
Name: имя, dtype: str

In [ ]:
df_clean = df_dirty.fillna({'город': 'Неизвестно', 'возраст': 0, 'зарплата': 0})
df_clean.to_csv('сотрудники_clean.csv', index=False, encoding='utf-8')
print('сохранено')

сохранено

In [ ]:
import numpy as np
import pandas as pd

data_dirty = {
    'имя': ['Никита', 'Анна', 'Иван', 'Мария', 'Олег'],
    'город': ['Пермь', 'Москва', None, 'Екатеринбург', 'Пермь'],
    'возраст': [19, 25, 31, None, 22],
    'зарплата': [35000, 90000, 60000, 75000, None]
}

df_dirty = pd.DataFrame(data_dirty)
df_dirty

      имя         город  возраст  зарплата
0  Никита         Пермь     19.0   35000.0
1    Анна        Москва     25.0   90000.0
2    Иван           NaN     31.0   60000.0
3   Мария  Екатеринбург      NaN   75000.0
4    Олег         Пермь     22.0       NaN

In [ ]:
# Сколько пропусков в каждом столбце
df_dirty.isnull().sum()
# Удалить все строки где есть хотя бы один NaN
df_dirty.dropna()
# Заполнить пропуски конкретным значением
df_dirty.fillna({'город': 'Неизвестно', 'возраст': 0, 'зарплата': 0})

      имя         город  возраст  зарплата
0  Никита         Пермь     19.0   35000.0
1    Анна        Москва     25.0   90000.0
2    Иван    Неизвестно     31.0   60000.0
3   Мария  Екатеринбург      0.0   75000.0
4    Олег         Пермь     22.0       0.0

In [ ]:
# Или одно из двух — хотя бы одно условие True
df[(df['город'] == 'Пермь') | (df['зарплата'] > 80000)]

      имя   город  возраст  зарплата
0  Никита   Пермь       19     35000
1    Анна  Москва       25     90000
2    Иван   Пермь       31     60000

In [ ]:
# По возрастанию
df.sort_values('зарплата')

      имя         город  возраст  зарплата
0  Никита         Пермь       19     35000
2    Иван         Пермь       31     60000
3   Мария  Екатеринбург       22     75000
1    Анна        Москва       25     90000

In [ ]:
# Средняя зарплата по городам
df.groupby('город')['зарплата'].mean()

город
Екатеринбург    75000.0
Москва          90000.0
Пермь           47500.0
Name: зарплата, dtype: float64

In [ ]:
# Количество человек в каждом городе
df.groupby('город')['имя'].count()

город
Екатеринбург    1
Москва          1
Пермь           2
Name: имя, dtype: int64

In [ ]:
df['город'].value_counts()

город
Пермь           2
Москва          1
Екатеринбург    1
Name: count, dtype: int64

In [ ]:
# По убыванию
df.sort_values('зарплата', ascending=False)

      имя         город  возраст  зарплата
1    Анна        Москва       25     90000
3   Мария  Екатеринбург       22     75000
2    Иван         Пермь       31     60000
0  Никита         Пермь       19     35000

In [ ]:
# Булева фильтрация — выбрать строки где возраст больше 20
df[df['возраст'] > 20]

     имя         город  возраст  зарплата
1   Анна        Москва       25     90000
2   Иван         Пермь       31     60000
3  Мария  Екатеринбург       22     75000

In [ ]:
# Загружаем CSV в DataFrame
df2 = pd.read_csv('сотрудники.csv')
df2

      имя         город  возраст  зарплата
0  Никита         Пермь       19     35000
1    Анна        Москва       25     90000
2    Иван         Пермь       31     60000
3   Мария  Екатеринбург       22     75000

In [ ]:
# Создаём тестовый CSV-файл
import csv

with open('сотрудники.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['имя', 'город', 'возраст', 'зарплата'])
    writer.writerow(['Никита', 'Пермь', 19, 35000])
    writer.writerow(['Анна', 'Москва', 25, 90000])
    writer.writerow(['Иван', 'Пермь', 31, 60000])
    writer.writerow(['Мария', 'Екатеринбург', 22, 75000])

print('файл создан')

файл создан

In [ ]:
# iloc — выбор по номеру строки (порядковый номер)
print(df.iloc[0])   # первая строка
print('---')
print(df.iloc[2])   # третья строка

# loc — выбор по индексу (в нашем случае совпадает с номером)
print('---')
print(df.loc[1])    # строка с индексом 1

имя         Никита
город        Пермь
возраст         19
зарплата     35000
Name: 0, dtype: object
---
имя          Иван
город       Пермь
возраст        31
зарплата    60000
Name: 2, dtype: object
---
имя           Анна
город       Москва
возраст         25
зарплата     90000
Name: 1, dtype: object

In [ ]:
# Выбор одного столбца — возвращает Series
print(df['имя'])
print(type(df['имя']))

# Выбор нескольких столбцов — возвращает DataFrame
df[['имя', 'зарплата']]

0    Никита
1      Анна
2      Иван
3     Мария
Name: имя, dtype: str
<class 'pandas.Series'>

      имя  зарплата
0  Никита     35000
1    Анна     90000
2    Иван     60000
3   Мария     75000

In [ ]:
df.head(2)
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   имя       4 non-null      str
 1   город     4 non-null      str
 2   возраст   4 non-null      int64
 3   зарплата  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

         возраст      зарплата
count   4.000000      4.000000
mean   24.250000  65000.000000
std     5.123475  23452.078799
min    19.000000  35000.000000
25%    21.250000  53750.000000
50%    23.500000  67500.000000
75%    26.500000  78750.000000
max    31.000000  90000.000000

In [ ]:
# Создаём DataFrame из словаря
data = {
    'имя': ['Никита', 'Анна', 'Иван', 'Мария'],
    'город': ['Пермь', 'Москва', 'Пермь', 'Екатеринбург'],
    'возраст': [19, 25, 31, 22],
    'зарплата': [35000, 90000, 60000, 75000]
}

df = pd.DataFrame(data)
df

      имя         город  возраст  зарплата
0  Никита         Пермь       19     35000
1    Анна        Москва       25     90000
2    Иван         Пермь       31     60000
3   Мария  Екатеринбург       22     75000

In [ ]:
import pandas as pd
print(pd.__version__)

3.0.5